In [12]:
# import pandas
import pandas as pd
# read csv
df = pd.read_csv('data/dafeatures.csv')
# Convert the DataFrame to a Dictionary
# data_dict = data.to_dict(orient='records')
df.head()

,Unnamed: 0,id,genre,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,preview_url
0,0,3HiFEoic67xzOhd1gBgDhg,Classical,0.263,0.00668,8,-31.999,0,0.0442,0.995,0.8930,0.0947,0.0550,69.197,212853,3,NaN
1,1,3HiFEoic67xzOhd1gBgDhg,Classical,0.263,0.00668,8,-31.999,0,0.0442,0.995,0.8930,0.0947,0.0550,69.197,212853,3,NaN
2,2,3HiFEoic67xzOhd1gBgDhg,Classical,0.263,0.00668,8,-31.999,0,0.0442,0.995,0.8930,0.0947,0.0550,69.197,212853,3,NaN
3,3,3HiFEoic67xzOhd1gBgDhg,Classical,0.263,0.00668,8,-31.999,0,0.0442,0.995,0.8930,0.0947,0.0550,69.197,212853,3,NaN
4,4,1QxMIioUmAxh7nlhdQuQvd,Classical,0.131,0.29500,1,-14.984,0,0.0373,0.847,0.0259,0.1250,0.0426,94.727,160968,3,https://p.scdn.co/mp3-preview/e8bb64944740497a...

In [13]:
nan_counts = df['preview_url'].isna().groupby(df['genre']).sum()

print("NaN counts in 'url' column split by 'genre':\n", nan_counts)

NaN counts in 'url' column split by 'genre':
 genre
Classical     683
Country       495
Hip-Hop      1436
Metal         529
Pop          1011
RnB           900
Name: preview_url, dtype: int64

In [14]:
nan_counts = df['preview_url'].notna().groupby(df['genre']).sum()

print("Actual counts in 'url' column split by 'genre':\n", nan_counts)

Actual counts in 'url' column split by 'genre':
 genre
Classical    1293
Country      1373
Hip-Hop      2047
Metal        1582
Pop          1309
RnB          1603
Name: preview_url, dtype: int64

In [20]:
# duplicate_rows_column1 = df[df.duplicated(subset=['preview_url'], keep=False)]

# print("Duplicate rows in 'Column1':")
# print(duplicate_rows_column1)
# print(df.duplicated().sum())
df['preview_url'].value_counts()

preview_url
https://p.scdn.co/mp3-preview/fc780d2d7634024c170723c769cca145d298e53f?cid=b1b7bb35faa34eac9690da4b561aa86f    216
https://p.scdn.co/mp3-preview/eeeb6151d0049367b3ad3db0389e9e3b116c0774?cid=b1b7bb35faa34eac9690da4b561aa86f    216
https://p.scdn.co/mp3-preview/83e86903458eda0bd082214175d2bb75ceffdc64?cid=b1b7bb35faa34eac9690da4b561aa86f    125
https://p.scdn.co/mp3-preview/4b0178cf6991f59db18e12e2219ff11e27474b0a?cid=b1b7bb35faa34eac9690da4b561aa86f    125
https://p.scdn.co/mp3-preview/7c7e0e4419d101bcf73764f245639d7bc83b662a?cid=b1b7bb35faa34eac9690da4b561aa86f    125
                                                                                                              ...
https://p.scdn.co/mp3-preview/5cfeeb17dccaa55d84544507ee7cac5784f2a19a?cid=b1b7bb35faa34eac9690da4b561aa86f      1
https://p.scdn.co/mp3-preview/c43118e4b3289a9aea6a9a46a55df727e97aceb3?cid=b1b7bb35faa34eac9690da4b561aa86f      1
https://p.scdn.co/mp3-preview/f726f4809f80dcc71969d1812262aae1e11d2f7e?cid=b1b7bb35faa34eac9690da4b561aa86f      1
https://p.scdn.co/mp3-preview/ef6e62fcc3ebb145726c75fb4c136e0f296453b6?cid=b1b7bb35faa34eac9690da4b561aa86f      1
https://p.scdn.co/mp3-preview/c01bb7e77b63fcff40c659db3e1257e72a95f0c5?cid=b1b7bb35faa34eac9690da4b561aa86f      1
Name: count, Length: 2680, dtype: int64